theme: minima
title: My awesome blog
author: MarcusTurnerBSU
email: marcus.turner19@bathspa.ac.uk
description: > 
  Here is a list of my favourite things:
  - :cat2: :dog2: :rabbit: :baby_chick: 
  - :musical_note: :tv: :video_game:
  - :sunny: :snowflake: :snowman:
  - :soccer: :golf: :8ball: 
  - :pizza: :fries: 
  - :peach:

# social links
twitter_username: :joy:
github_username:  https://github.com/MarcusTurnerBSU

show_excerpts: true # set to false to remove excerpts on the homepage
